# -*- coding: utf-8 -*-
"""AIinCyberSecurity-LabAssignment1-2401830001-AdityaChouhan

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rhPV7HP4O3bDmOcy0yE-Lpj9h8awgVaD

# **LAB 1: Recognizing Cyber Threats Using Simple AI Rules**
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

# Load the dataset
df = pd.read_csv('simple_cyber_messages.csv')

# Display the first five messages
display(df.head())

# Display dataset size
print("Dataset shape:", df.shape)

"""# **Q1. Manual Threat Identification**"""

manual_table = df.head(10)[
    ['message_id', 'message', 'correct_category']
].copy()

# Important words/phrases identified manually
manual_table['important_words'] = [
    'meeting, scheduled',
    'suspended, click here, verify, password, urgently',
    'executable, trojan, infect',
    'encrypted, bitcoin, restore files',
    'library, returned',
    'prize, login, claim',
    'spyware, attachment',
    'locked files, ransom, payment',
    'official portal',
    'urgent, bank, verify, OTP'
]

# Manual classification
manual_table['manual_classification'] = manual_table['correct_category']

display(manual_table)

"""# **Q2. Keyword Lists and Rule-Based Classifier**"""

# Keyword lists for each cyber-threat category
RULE_KEYWORDS = {
    'Phishing': [
        'click here',
        'verify',
        'password',
        'urgent',
        'otp',
        'prize',
        'bank',
        'login',
        'blocked'
    ],

    'Malware': [
        'malware',
        'virus',
        'infected',
        'attachment',
        'trojan',
        'spyware',
        'executable'
    ],

    'Ransomware': [
        'encrypted',
        'ransom',
        'bitcoin',
        'restore files',
        'locked files',
        'unlock',
        'payment demand'
    ]
}


# Rule-based classification function
def classify_message(text):

    # Convert message to lowercase
    text = str(text).lower()

    # Count matching keywords for each category
    scores = {
        category: sum(word in text for word in words)
        for category, words in RULE_KEYWORDS.items()
    }

    # Select category with the highest score
    predicted = max(scores, key=scores.get)

    # If no keywords are found, classify as Safe
    if scores[predicted] == 0:
        return 'Safe', '', 0

    # Find the keywords that matched
    matched = [
        word
        for word in RULE_KEYWORDS[predicted]
        if word in text
    ]

    return predicted, ', '.join(matched), scores[predicted]


# Test the classifier
test_message = "Urgent: click here to verify your password"

print("Test Message:")
print(test_message)

print("\nClassification Result:")
print(classify_message(test_message))

"""# **Q2: Test the classifier with four different messages**"""

test_messages = [
    "Urgent: click here to verify your password",
    "The attached executable contains a trojan.",
    "Your files are encrypted; pay bitcoin to restore files.",
    "The department meeting is scheduled for 2 PM."
]

for message in test_messages:
    category, keywords, score = classify_message(message)

    print("Message:", message)
    print("Predicted Category:", category)
    print("Matched Keywords:", keywords)
    print("Keyword Score:", score)
    print("-" * 70)

"""# **Q3. Complete Dataset Classification and Accuracy**

"""

# Apply the classifier to every message
results = df['message'].apply(classify_message)

# Store the results in the dataframe
df[['predicted_category', 'matched_keywords', 'keyword_score']] = pd.DataFrame(
    results.tolist(),
    index=df.index
)

# Check whether prediction is correct
df['correct'] = (
    df['correct_category'] == df['predicted_category']
)

# Calculate correct and incorrect predictions
correct_predictions = df['correct'].sum()
incorrect_predictions = len(df) - correct_predictions

# Calculate accuracy
accuracy = accuracy_score(
    df['correct_category'],
    df['predicted_category']
)

# Display complete classification table
display(
    df[
        [
            'message_id',
            'correct_category',
            'predicted_category',
            'matched_keywords',
            'keyword_score',
            'correct'
        ]
    ]
)

# Display final results
print("Correct predictions:", correct_predictions)
print("Incorrect predictions:", incorrect_predictions)
print(f"Accuracy: {accuracy * 100:.2f}%")

"""# **Q4. Risk Level and Recommended Action**"""

def add_risk_and_action(row):

    if row['predicted_category'] == 'Safe':
        return 'Low', 'Continue normal caution.'

    if (
        row['predicted_category'] == 'Ransomware'
        or row['keyword_score'] >= 2
    ):
        return (
            'High',
            'Do not click/open; isolate if required and report.'
        )

    return (
        'Medium',
        'Do not interact; verify the sender and report.'
    )


# Apply risk classification
risk_output = df.apply(
    add_risk_and_action,
    axis=1
)

# Add risk and action columns
df[['risk_level', 'recommended_action']] = pd.DataFrame(
    risk_output.tolist(),
    index=df.index
)

# Display the complete risk/action table
display(
    df[
        [
            'message_id',
            'predicted_category',
            'keyword_score',
            'risk_level',
            'recommended_action'
        ]
    ]
)

"""# **Q4. Bar Chart of Predicted Categories** #

"""

category_order = [
    'Safe',
    'Phishing',
    'Malware',
    'Ransomware'
]

category_counts = (
    df['predicted_category']
    .value_counts()
    .reindex(category_order, fill_value=0)
)

print("Category Counts:")
print(category_counts)

# Create bar chart
category_counts.plot(
    kind='bar',
    edgecolor='black'
)

plt.title('Predicted Message Categories')
plt.xlabel('Category')
plt.ylabel('Number of Messages')
plt.xticks(rotation=0)

plt.tight_layout()
plt.show()

"""# **Q5. Responsible Use and Reflection**"""

responsible_use = [
    "Privacy: Remove personal identifiers before analysis.",
    "Bias: Keyword lists may not cover every writing style or variation.",
    "False alarms: Safe messages may contain warning words.",
    "Accountability: Humans remain responsible for the final decision.",
    "Human review: High-risk or unclear cases should be checked by a human."
]

for point in responsible_use:
    print("-", point)

"""# **- Live/New Message Demonstration**"""

new_message = "Urgent: click here to verify your password"

result = classify_message(new_message)

print("New Message:")
print(new_message)

print("\nClassification Result:")
print(result)

"""# **- Save Final Results**

"""

df.to_csv(
    'Lab1_Final_Result.csv',
    index=False
)

print("Saved: Lab1_Final_Result.csv")

"""# **- Conclusion**

*This lab demonstrated how simple rule-based AI can be used to identify common cyber threats such as Phishing, Malware, and Ransomware. The classifier uses predefined keywords and counts matching indicators in each message. Out of 28 messages, 27 were classified correctly, giving an accuracy of 96.43%. One message was incorrectly classified because the wording was different from the exact keyword phrase used in the rules. This shows that keyword-based systems are transparent and easy to understand, but they may fail when attackers use different wording or variations. Therefore, such systems should be used as an aid to human analysts rather than as fully autonomous decision-making systems. Privacy protection and human review are also important when handling potentially sensitive cyber-security messages.*

# **- Observations**

1. Phishing messages commonly contained words such as urgent, verify, password, OTP, bank, login, and click here.
2. Malware messages contained indicators such as executable, trojan, spyware, attachment, and infected.
3. Ransomware messages commonly contained terms such as encrypted, ransom, bitcoin, restore files, and locked files.
4. Safe messages generally did not contain the predefined threat keywords.
5. The classifier achieved 96.43% accuracy on the supplied dataset.
6. The incorrect prediction demonstrated that exact keyword matching can miss variations in wording.
7. Risk levels were assigned according to the predicted category and keyword score.
8. Human review is necessary for high-risk or uncertain messages. *italicized text*
"""